[features]
seeds = false

[programs.localnet]
blockchain_credential_manager = "5ZJTTxRsgehbwPeZcjz98xcXA9z8QeiSwMrthLrmwsNQ"

[programs.devnet]
blockchain_credential_manager = "5ZJTTxRsgehbwPeZcjz98xcXA9z8QeiSwMrthLrmwsNQ"

[programs.mainnet]
blockchain_credential_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/lucas/.config/solana/id.json"

[workspace]
types = "./app/src/idl"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p ./app/src/idl && cp ./target/idl/blockchain_credential_manager.json ./app/src/idl/blockchain_credential_manager.json"
