[features]
seeds = false

[programs.localnet]
blockchain_credential_manager = "4Y8nXDhUJ4tGM2n8485ZErt3tVhGa8xRTN1ozMDWEkqE"

[programs.devnet]
blockchain_credential_manager = "4Y8nXDhUJ4tGM2n8485ZErt3tVhGa8xRTN1ozMDWEkqE"

[programs.mainnet]
blockchain_credential_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "../app/src/idl"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json tests/**/*.ts"
copy-idl = "mkdir -p ../app/src/idl && cp ./target/idl/blockchain_credential_manager.json ../app/src/idl/blockchain_credential_manager.json"
copy-types = "cp ./target/types/blockchain_credential_manager.ts ../app/src/idl/blockchain_credential_manager.ts"
